# -*- coding: utf-8 -*-
"""Crypto-MachineLearningProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBz1Zp0NsbDuLsKXVBj4DkoQc98wVyfr
"""

!pip install pandas numpy matplotlib statsmodels scipy seaborn yfinance pmdarima

import pandas as pd  # For data manipulation
import numpy as np  # For numerical operations
import matplotlib.pyplot as plt  # For data visualization
import seaborn as sns  # For enhanced plots
import statsmodels.api as sm  # For ARIMA and statistical tests
from statsmodels.tsa.stattools import adfuller  # Augmented Dickey-Fuller test for stationarity
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf  # ACF/PACF plots
from statsmodels.tsa.arima.model import ARIMA  # ARIMA model
from scipy.stats import zscore  # For data normalization if needed
import yfinance as yf  # To fetch cryptocurrency data
import pmdarima as pm  # Auto ARIMA for model selection
from sklearn.metrics import mean_squared_error  # RMSE for model evaluation

file_path = "data/ethereum_data.csv"
df = pd.read_csv(file_path, skiprows=2)  # Skip both rows
df.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
print(df.head())